import { useState, useEffect } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import Layout from "../components/Layout";
import "../styles/decision.css";
import { getClaimReport } from "../services/reportsService";

function Decision() {
    const navigate = useNavigate();
    const [searchParams] = useSearchParams();
    const claimId = searchParams.get("id");

    const [report, setReport]   = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError]     = useState("");

    useEffect(() => {
        if (!claimId) {
            setError("No claim ID provided. Redirecting to dashboard...");
            setLoading(false);
            const timer = setTimeout(() => navigate("/dashboard"), 2000);
            return () => clearTimeout(timer);
        }

        getClaimReport(claimId)
            .then(setReport)
            .catch((err) => setError(err.message || "Failed to load decision report."))
            .finally(() => setLoading(false));
    }, [claimId]);

    const verdict        = report?.verdict || "CONDITIONAL";
    const summary        = report?.procedure_name || "Claim Requires Review";
    const description    = `STG ${report?.diagnosis_code || "N/A"} | ALOS: ${report?.alos_range?.join("-") || "N/A"} days | Score: ${report?.compliance_score || 0}%`;
    
    const failedRules    = report?.failed_rules || [];
    const matchedRules   = report?.matched_rules || [];

    const payableAmount  = report?.payable_amount ?? "—";
    const totalClaimed   = report?.total_claimed ?? "—";

    const verdictClass = {
        "APPROVED":    "approved",
        "REJECTED":    "rejected",
        "CONDITIONAL": "conditional",
    }[String(verdict).toUpperCase()] ?? "conditional";

    const nextPath = claimId ? `/reports?id=${claimId}` : "/reports";

    return (
        <Layout>
            <div className="decision-page">
                <div className="decision-header">
                    <h1>AI Decision Engine</h1>
                    <p>Final claim verdict generated by AI analysis based on NHA Guidelines</p>
                </div>

                {error && <p style={{ color: "#ef4444", marginBottom: "1rem" }}>{error}</p>}

                <div className="decision-result">
                    <div className={`decision-badge ${verdictClass}`}>
                        {loading ? "…" : verdict}
                    </div>
                    <h2>{loading ? "Loading decision..." : summary}</h2>
                    <p>{loading ? "" : description}</p>
                </div>

                {!loading && (
                    <div className="decision-grid">
                        {/* Reasons for Decision (Failed Rules) */}
                        <div className="decision-card">
                            <h2>Reasons for Verdict</h2>
                            {failedRules.length > 0 ? (
                                failedRules.map((rule, index) => (
                                    <div className="reason-item" key={index} style={{ borderLeft: rule.part === "TMS" ? "4px solid #ef4444" : "4px solid #f59e0b" }}>
                                        <strong>[{rule.id}]</strong> {rule.description}
                                        {rule.fix && <div style={{ fontSize: "12px", color: "#666", marginTop: "4px" }}>Fix: {rule.fix}</div>}
                                    </div>
                                ))
                            ) : (
                                <p style={{ color: "#22c55e", fontWeight: "bold" }}>No compliance violations found. Fully compliant.</p>
                            )}
                        </div>

                        {/* Evidence (Matched Rules) */}
                        <div className="decision-card">
                            <h2>Evidence & Validations</h2>
                            {matchedRules.length > 0 ? (
                                matchedRules.map((rule, index) => (
                                    <div className="evidence-item" key={index}>
                                        ✅ {rule.description}
                                    </div>
                                ))
                            ) : (
                                <p style={{ color: "#94a3b8" }}>No evidence recorded.</p>
                            )}
                        </div>
                    </div>
                )}

                <div className="payout-box">
                    <h2>Suggested Payable Amount</h2>
                    <h1>{loading ? "…" : `₹${Number(payableAmount).toLocaleString("en-IN")}`}</h1>
                    <p>Total Claimed: {loading ? "…" : `₹${Number(totalClaimed).toLocaleString("en-IN")}`}</p>
                </div>

                <button className="next-btn" onClick={() => navigate(nextPath)}>
                    Generate Final Report →
                </button>
            </div>
        </Layout>
    );
}

export default Decision;