import { useNavigate } from "react-router-dom";
import Layout from "../components/Layout";
import "../styles/decision.css";

function Decision() {
    const navigate = useNavigate();

    const evidences = [
        "Treatment timeline verified",
        "Lab reports matched",
        "Prescription validated",
        "Billing anomaly detected",
    ];

    const reasons = [
        "Claim follows major STG guidelines",
        "Minor billing mismatch found",
        "Manual verification recommended",
    ];

    return (
        <Layout>
            <div className="decision-page">

                <div className="decision-header">
                    <h1>AI Decision Engine</h1>
                    <p>
                        Final claim verdict generated by AI analysis
                    </p>
                </div>

                <div className="decision-result">

                    <div className="decision-badge conditional">
                        CONDITIONAL
                    </div>

                    <h2>Claim Requires Manual Review</h2>

                    <p>
                        Claim passed core validation but has
                        minor anomalies
                    </p>

                </div>

                <div className="decision-grid">

                    {/* Reasons */}
                    <div className="decision-card">
                        <h2>Reasons</h2>

                        {reasons.map((item, index) => (
                            <div
                                className="reason-item"
                                key={index}
                            >
                                {item}
                            </div>
                        ))}
                    </div>

                    {/* Evidence */}
                    <div className="decision-card">
                        <h2>Evidence</h2>

                        {evidences.map((item, index) => (
                            <div
                                className="evidence-item"
                                key={index}
                            >
                                {item}
                            </div>
                        ))}
                    </div>

                </div>

                <div className="payout-box">
                    <h2>Suggested Payable Amount</h2>
                    <h1>₹32,000</h1>
                    <p>Total Claimed: ₹42,000</p>
                </div>

                <button
                    className="next-btn"
                    onClick={() => navigate("/reports")}
                >
                    Generate Final Report →
                </button>

            </div>
        </Layout>
    );
}

export default Decision;